# Generated by Django 6.0 on 2025-12-18 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.county'),
        ),
    ]
