# Generated by Django 4.2.27 on 2025-12-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('emergency_only', 'Emergency Only'), ('closed', 'Closed')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='facility',
            name='last_status_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
