# Generated by Django 4.2.27 on 2026-03-11 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_facility_availability_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='accepts_nhif',
            new_name='accepts_sha',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='nhif_code',
            new_name='sha_code',
        ),
    ]
