# Generated by Django 4.2.27 on 2026-04-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_add_location_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='is_customized',
            field=models.BooleanField(default=False, help_text="Whether we've manually enhanced this facility"),
        ),
        migrations.AddField(
            model_name='facility',
            name='is_published_in_mfl',
            field=models.BooleanField(default=False, help_text='Whether MFL has published this facility'),
        ),
        migrations.AddField(
            model_name='facility',
            name='last_mfl_sync',
            field=models.DateTimeField(blank=True, help_text='Last sync with MFL API', null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='mfl_uuid',
            field=models.UUIDField(blank=True, help_text="MFL's internal UUID", null=True, unique=True),
        ),
    ]
