# Generated by Django 4.2.27 on 2026-04-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0007_facility_is_customized_facility_is_published_in_mfl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='mfl_code',
            field=models.CharField(blank=True, help_text='MFL facility code', max_length=20),
        ),
        migrations.AddField(
            model_name='facility',
            name='ward',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
