# Generated by Django 4.2.27 on 2026-06-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0009_add_filter_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='facility',
            name='facility_constituency_idx',
        ),
        migrations.RemoveIndex(
            model_name='facility',
            name='facility_town_idx',
        ),
        migrations.RemoveIndex(
            model_name='facility',
            name='facility_24hr_idx',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='accepts_sha',
            new_name='accepts_nhif',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='sha_code',
            new_name='nhif_code',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='is_customized',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='is_published_in_mfl',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='last_mfl_sync',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='location',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='mfl_code',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='mfl_uuid',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='ward',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('general', 'General Medicine'), ('specialist', 'Specialist Care'), ('emergency', 'Emergency Services'), ('diagnostic', 'Diagnostic Services'), ('maternal', 'Maternal & Child Health'), ('pharmacy', 'Pharmacy Services')], max_length=50),
        ),
    ]
