# Generated by Django 6.0 on 2025-12-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='region',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
