# Generated by Django 4.2.27 on 2026-04-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MFLSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=20)),
                ('facilities_created', models.IntegerField(default=0)),
                ('facilities_updated', models.IntegerField(default=0)),
                ('facilities_skipped', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
        ),
    ]
